add jest config and sample test file
medic/interoperability pull request #35
Opened 2023-02-13 14:05 UTC by njogz

# Description

Add jest configuration and one unit test

medic/interoperability#33

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-02-17 20:55 UTC, lorerod requested changes
Thanks, @njogz for this initiative. 
I added a suggestion for the test files that may be helpful. Let me know what you think.
Also, for curiosity, why did you choose jest instead of mocha, as in cht-core?

2023-02-17 20:55 UTC, lorerod commented on mediator/jest.config.js
> +};
Having this file inside a /mediator/tests/ directory is better.

2023-02-17 20:55 UTC, lorerod commented on mediator/src/utils/patient.spec.ts
> +});
Like my previous comment, having this file inside a /mediator/tests/ directory is better.

2023-02-22 16:30 UTC, andrablaj requested changes
Thanks @njogz for adding the first test! 

I committed an update to the troubleshooting page and shared some comments as the test failed on my side.

2023-02-22 16:30 UTC, andrablaj commented on mediator/src/utils/patient.spec.ts
> +test("genereateFHIRPatientResource produces the correct format", () => {
```suggestion
test("generateFHIRPatientResource produces the correct format", () => {
```

2023-02-22 16:30 UTC, andrablaj commented on mediator/src/utils/patient.spec.ts
> +import { genereateFHIRPatientResource } from "./patient";
```suggestion
import { generateFHIRPatientResource } from "./patient";
```

2023-02-22 16:30 UTC, andrablaj commented on mediator/src/utils/patient.spec.ts
> +  const FHIRPatient = genereateFHIRPatientResource(chtPatient);
```suggestion
  const FHIRPatient = generateFHIRPatientResource(chtPatient);
```

2023-02-22 16:30 UTC, andrablaj commented on mediator/src/utils/patient.spec.ts
> +    date_of_birth: "200 0-01-01"
I had to change it to: 
```suggestion
    date_of_birth: "2000-01-01"
```

2023-02-22 16:30 UTC, andrablaj commented on mediator/src/utils/patient.spec.ts
> +    birthDate: '200 0-01-01'
I had to change it to: 
```suggestion
    date_of_birth: "2000-01-01"
```

2023-02-22 16:30 UTC, andrablaj commented on mediator/src/utils/patient.spec.ts
> +    birthDate: '200 0-01-01'
The unit test is failing with:

> 
> expect(received).toEqual(expected) // deep equality
> 
>     - Expected  - 1
>     + Received  + 1
> 
>     @@ -1,7 +1,7 @@
>       Object {
>     -   "birthDate": "2000-01-01",
>     +   "birthDate": "2000-01-01T00:00:00.000Z",

2023-02-23 10:26 UTC, andrablaj requested changes
Added a few minor suggestions. Otherwise looks good, to start with.

2023-02-23 10:26 UTC, andrablaj commented on mediator/README.md
>  1. Run `npm install` to isntall the dependencies.
```suggestion
1. Run `npm install` to install the dependencies.
```

2023-02-23 10:26 UTC, andrablaj commented on mediator/README.md
> +1. Run `npm test` to run the tests.
```suggestion
1. Navigate to `/mediator` folder. Run `npm test` to run the tests.
```

2023-02-23 10:53 UTC, andrablaj approved these changes

2023-02-23 13:30 UTC, lorerod approved these changes
Thanks @njogz

2023-02-24 13:52 UTC, merged