1 openhim configuration
medic/interoperability pull request #4
Opened 2023-01-12 23:26 UTC by samuelimoisili

### Description
- Added a `startup.sh` script to help automate the startup and shutdown process.
- Added a `configurator` which sets up the `user`, `client` and `channel` details on OpenHIM. It also registers a `channel` for `hapi-fihr`.
- Removed the bloated OpenHIE instant docker setup and replaced it with a leaner docker compose setup.

2023-01-13 10:12 UTC, samuelimoisili commented on configurator/libs/generators.js
> +    await generatePassword(password);
If for some reason `generatePassword` fails, I don't think we want it to fail gracefully.

2023-01-13 10:27 UTC, samuelimoisili commented on package.json
> +    "init": "./startup.sh init",
They're development commands, I don't think it's important for getting started. We could add them when creating a more detailed guide.

2023-01-13 12:28 UTC, andrablaj commented
@samuelimoisili @njogz can you please rename this repo to `interoperability`, as it is not a placeholder anymore? Thanks!

2023-01-13 17:42 UTC, lorerod commented on README.md
> +1. Run `./startup.sh init` to start-up the docker containers on the first run or after calling `./startup.sh destroy`. Use `./startup.sh up` for subsequent runs after calling `init` without calling `
```suggestion
1. Run `./startup.sh init` to start-up the docker containers on the first run or after calling `./startup.sh destroy`. Use `./startup.sh up` for subsequent runs after calling `init` without calling `destroy`.
```

2023-01-13 17:42 UTC, lorerod commented on README.md
> +1. Run `./startup.sh init` to start-up the docker containers on the first run or after calling `./startup.sh destroy`. Use `./startup.sh up` for subsequent runs after calling `init` without calling `
Please summarize what will be created with this command.

2023-01-13 17:42 UTC, lorerod commented on README.md
> +1. Once logged in, visit https://localhost:9000/#!/mediators and select the only mediator with the `Name` 'mediator'.
I'm seeing a mediator with the `Name` 'Loss to Follow Up Mediator'

2023-01-13 17:42 UTC, lorerod commented on README.md
> +1. Once logged in, visit https://localhost:9000/#!/mediators and select the only mediator with the `Name` 'mediator'.
![Captura de pantalla 2023-01-13 a la(s) 14 22 43](https://user-images.githubusercontent.com/21312057/212380798-95bc2aa7-aadb-4838-ac5d-6b0b14dd1965.png)

2023-01-13 17:42 UTC, lorerod commented on README.md
> +1. You can test the mediator by running `curl -X GET http://localhost:5001/scaffold -H "Authorization: Basic $(echo -n interop-client:interop-password | base64)"`. You should get the following respon
I'm getting `HTTP/1.1 404 Not Found` 
And can see this in openhim-core logs:
```
info: interop-client could NOT be authenticated, trying next auth mechanism if any...
info: Could NOT authenticate via TLS: undefined, trying next auth mechanism if any...
info: No channel matched the request /scaffold
```

2023-01-13 17:42 UTC, lorerod commented on README.md
>  This is a placeholder for 2023 interoperability project
Please summarize what is this repository about

2023-01-13 17:42 UTC, lorerod commented on README.md
>  This is a placeholder for 2023 interoperability project
```suggestion

```

2023-01-15 14:28 UTC, lorerod requested changes
Thanks @samuelimoisili for considering my suggestions. I just have one dude with the instructions. I'm using a Mac with macOS 13.1 and Docker Desktop Version 4.15.0; Engine: 20.10.21; Compose: 1.29.2 and I'm not getting the `{"status": "success" }` response when running curl.

2023-01-15 14:28 UTC, lorerod commented on README.md
> +1. You can test the mediator by running `curl -X GET http://localhost:5001/mediator -H "Authorization: Basic $(echo -n interop-client:interop-password | base64)"`. You should get the following respon
@samuelimoisili when running the curl command I'm getting:
`curl: (3) URL using bad/illegal format or missing URL`
And openhim-core logs shows:
```
2023-01-15 11:24:04 2023-01-15T14:24:04.404Z [worker1] info: starting job: generate transaction alerts, Last Ran at: Sun Jan 15 2023 14:24:04 GMT+0000 (Coordinated Universal Time)
2023-01-15 11:24:04 2023-01-15T14:24:04.424Z [worker1] info: Job generate transaction alerts has completed
2023-01-15 11:24:04 2023-01-15T14:24:04.429Z [worker1] info: starting job: auto retry failed transactions, Last Ran at: Sun Jan 15 2023 14:24:04 GMT+0000 (Coordinated Universal Time)
2023-01-15 11:24:04 2023-01-15T14:24:04.435Z [worker1] info: Job auto retry failed transactions has completed
2023-01-15 11:24:13 2023-01-15T14:24:13.233Z [worker1] info: No basic auth details supplied, trying next auth mechanism if any...
2023-01-15 11:24:13 2023-01-15T14:24:13.234Z [worker1] info: Could NOT authenticate via TLS: undefined, trying next auth mechanism if any...
2023-01-15 11:24:13 2023-01-15T14:24:13.241Z [worker1] info: The channel that matches the request /mediator is: Mediator
2023-01-15 11:24:13 2023-01-15T14:24:13.242Z [worker1] info: The request, '/mediator', is not authorised to access any channels.
```

2023-01-15 15:32 UTC, lorerod commented on README.md
> +1. You can test the mediator by running `curl -X GET http://localhost:5001/mediator -H "Authorization: Basic $(echo -n interop-client:interop-password | base64)"`. You should get the following respon
I also tried using the following command (generated by Postman): `curl -X GET -i http://localhost:5001/mediator -H 'authorization: Basic aW50ZXJvcC1jbGllbnQ6aW50ZXJvcC1wYXNzd29yZA==' -H 'cache-control: no-cache' -H 'postman-token: 0817aeb7-ea2d-f5d7-612b-38c6325a0b74'` and got: `HTTP 401 Unauthorized`
And openhim-core logs shows:
```
2023-01-15 12:25:58 2023-01-15T15:25:58.600Z [worker1] info: interop-client could NOT be authenticated, trying next auth mechanism if any...
2023-01-15 12:25:58 2023-01-15T15:25:58.601Z [worker1] info: Could NOT authenticate via TLS: undefined, trying next auth mechanism if any...
2023-01-15 12:25:58 2023-01-15T15:25:58.611Z [worker1] info: The channel that matches the request /mediator is: Mediator
2023-01-15 12:25:58 2023-01-15T15:25:58.611Z [worker1] info: The request, '/mediator', is not authorised to access any channels.
2023-01-15 12:26:03 2023-01-15T15:26:03.620Z [worker1] info: HTTP socket timeout reached
```

2023-01-16 14:53 UTC, lorerod approved these changes
Thanks, @samuelimoisili. I finally got this working locally with the instructions.

2023-01-16 15:05 UTC, merged