Update README
medic/interoperability pull request #42
Opened 2023-03-01 17:02 UTC by andrablaj

# Description

Update and clarify existing README. Add a sequence diagram.

#25 

# Code review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://docs.communityhealthtoolkit.org/contribute/code/style-guide/), documented if necessary.
- [ ] Documented: Configuration and user documentation on [cht-docs](https://github.com/medic/cht-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in the release notes.
 
# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

2023-03-07 11:51 UTC, andrablaj commented
@njogz @samuelimoisili when using Docker setup, I am not sure if:

> Create a file named `.env` copy over the contents of `.env.template` and update the `CHT_USERNAME` and `CHT_PASSWORD` values with the admin credentials of your CHT instance.

is still needed. Can you please help clarify that bit?

2023-03-14 20:13 UTC, lorerod requested changes
Thank you @andrablaj for this! . I added a couple of suggestions that may be helpful. Let me know what you think.

2023-03-14 20:13 UTC, lorerod commented on README.md
>  1. Set up a local CHT instance using [these instructions](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/).
Following [these instructions](https://docs.communityhealthtoolkit.org/apps/tutorials/local-setup/) I get to a port conflict with interoperability. More detail on issue [comment](https://github.com/medic/interoperability/issues/24#issuecomment-1468453919)

2023-03-16 08:44 UTC, andrablaj commented on README.md
> +
They don't need to run the container as they already did via` ./startup init.` These steps are only to check the CHT configuration. If you have suggestions on how to make it clearer, please comment here.

2023-03-16 09:20 UTC, andrablaj commented
@lorerod you requested to add the OpenHIM instance credentials in the `README`. We might not want to share them publicly, so I will not add them for now. This can be discussed in the next weekly call. 
FYI @njogz

2023-03-16 09:21 UTC, andrablaj commented on README.md
> +* **OpenHIM Admin Console** - [https://interoperability.dev.medicmobile.org](https://interoperability.dev.medicmobile.org)
Not sure if we want to share the instance credentials publicly. To be discussed in a next call with the team.

2023-03-21 10:02 UTC, merged